// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMLRDAemkSiFu9HB1uyjEToG7N7Jt_O6Q',
    appId: '1:128343086777:web:883c94bc0f60fc963c6d68',
    messagingSenderId: '128343086777',
    projectId: 'maya-music-app',
    authDomain: 'maya-music-app.firebaseapp.com',
    databaseURL: 'https://maya-music-app.firebaseio.com',
    storageBucket: 'maya-music-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxLpo8AkXcLjaMxRbNW_AIqNIKHCuEcmM',
    appId: '1:128343086777:android:d3462bc0c0f454943c6d68',
    messagingSenderId: '128343086777',
    projectId: 'maya-music-app',
    databaseURL: 'https://maya-music-app.firebaseio.com',
    storageBucket: 'maya-music-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlR91dmEBn7nNsm5JEL29LYVWV4WPcYI',
    appId: '1:128343086777:ios:6715000cf6b7654b3c6d68',
    messagingSenderId: '128343086777',
    projectId: 'maya-music-app',
    databaseURL: 'https://maya-music-app.firebaseio.com',
    storageBucket: 'maya-music-app.appspot.com',
    androidClientId: '128343086777-1k6smp1j32s1e7qup39t2fnfk7qonqde.apps.googleusercontent.com',
    iosClientId: '128343086777-lo0d43u57fbc6irsvp719ne025ok8a2g.apps.googleusercontent.com',
    iosBundleId: 'com.khandokeranan.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGlR91dmEBn7nNsm5JEL29LYVWV4WPcYI',
    appId: '1:128343086777:ios:6715000cf6b7654b3c6d68',
    messagingSenderId: '128343086777',
    projectId: 'maya-music-app',
    databaseURL: 'https://maya-music-app.firebaseio.com',
    storageBucket: 'maya-music-app.appspot.com',
    androidClientId: '128343086777-1k6smp1j32s1e7qup39t2fnfk7qonqde.apps.googleusercontent.com',
    iosClientId: '128343086777-lo0d43u57fbc6irsvp719ne025ok8a2g.apps.googleusercontent.com',
    iosBundleId: 'com.khandokeranan.googleAuth',
  );
}
